import { Injectable } from '@angular/core';
import { Gastronomia } from '../gastronomia';

@Injectable({
  providedIn: 'root'
})
export class InMemoryDataService {

  createDb(){

    const gastronomias: Gastronomia [] = [
      //Gastronomia Mediterranea
      { id:1,
        img:'',
        cultura:'Mediterránea',
        region: 'Espania',
        descripcion: 'La gastronomía Española se basa en una cocina de origen que oscila entre el estilo rural y el costero, y que representa una diversidad fruto de muchas culturas, así como de paisajes y climas. La cocina española está fuertemente influida a lo largo de su historia por los pueblos que conquistan su territorio, así como de los pueblos que posteriormente conquista y coloniza. Esta situación le ha proporcionado una gran variedad de técnicas culinarias e ingredientes.',
        platosPrincipales: ['Paella','Tortilla de Patatas','Gazpacho'],
        ingredientes: [{nombre:'Cebolla', categoria:'verdura'},
                      {nombre:'Huevos', categoria:'Proteina'},
                      {nombre:'Patatas', categoria:'Tuberculo'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Vinagre de Jerez', categoria:'Condimentos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Pollo', categoria:'Proteina'},
                      {nombre:'Conejo', categoria:'Proteina'},
                      {nombre:'Judias', categoria:'Legumbres'},
                      {nombre:'Alcachofa', categoria:'Hotalizas'},
                      {nombre:'Azafran', categoria:'Condimentos'},
                      {nombre:'Romero', categoria:'Condimentos'}],
        restaurantes: ['Azurmendi','Martin Berasategui','El Celler de Can Roca','Átrio']
      },
      { id:2,
        img:'',
        cultura:'Mediterránea',
        region: 'Portugal',
        descripcion: 'La gastronomía portuguesa puede encuadrarse en la cocina mediterránea y, como en esta, los tres ejes sobre los que gira la comida portuguesa son el pan, el vino y el aceite. No obstante, también se nota la influencia de las excolonias portuguesas de Asia, África y América (cocina brasileña) , sobre todo en el uso de las especias, que incluyen el piri piri, el pimentón y la canela. El fuerte carácter Atlántico hace a la cocina distinta en comparación con otras cocinas mediterráneas con el casi total desconocimiento de lentejas, berenjenas o cardo.',
        platosPrincipales: ['Bacalao','Francesinha','Caldo verde'],
        ingredientes: [{nombre:'Bacalao', categoria:'Proteinas'},
                      {nombre:'Vino Blanco', categoria:'Bebidas Alcoholicas'},
                      {nombre:'Patatas', categoria:'Tuberculo'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Cerveza', categoria:'Bebidas Alcoholicas'},
                      {nombre:'Lomo de Cerdo', categoria:'Proteinas'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Jamón', categoria:'Proteinas'},
                      {nombre:'Salchichas', categoria:'Proteinas'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Col Gallega', categoria:'Hotalizas'},
                      {nombre:'Chorizo Ahumado', categoria:'Proteinas'}],
        restaurantes: ['Casa de Chá da Boa Nova','The Yeatman','Ocean','Vila Joya']
      },
      { id:3,
        img:'',
        cultura:'Mediterránea',
        region: 'Grecia',
        descripcion: 'La comida griega sigue un patrón de dieta totalmente mediterráneo, basado en el uso de pocas carnes e hidratos de carbono y muchos y muy variados alimentos vegetales. También tiene mucha presencia el aceite de oliva, que contiene fundamentalmente grasas monoinsaturadas y disminuye el riesgo cardiovascular.',
        platosPrincipales: ['Htipiti griego','buñuelos de calabacín','Ensalada griega'],
        ingredientes: [{nombre:'Calabacín', categoria:'Vegetales'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Pepino', categoria:'Vegetales'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Aceitunas', categoria:'Vegetales'},
                      {nombre:'Oréngano', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hierbabuena', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Queso Feta', categoria:'Proteinas'},
                      {nombre:'Vinagre de Jerez', categoria:'Condimentos'}],
        restaurantes: ['Kikis Tavern','Medoussa','Ocean','Goodys','Aspro Alogo']
      },
      { id:4,
        img:'',
        cultura:'Mediterránea',
        region: 'Turquia',
        descripcion: 'La cocina turca es una de las más internacionales del mundo. Cuenta con claras influencias de su pasado otomano y de la cultura árabe. Es rica en carnes, siendo el Kebab su plato más exportado, y en especias, por lo que sus platos tienen un sabor único.',
        platosPrincipales: ['Pilav','Muhlama','Balik Ekmek'],
        ingredientes: [{nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Pimienta Negra', categoria:'Condimentos'},
                      {nombre:'Lomo de Caballa', categoria:'Proteinas'},
                      {nombre:'Harina de Maiz', categoria:'Cereales'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Queso Colot', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hoas de Lechuga', categoria:'Hortalizas'}],
        restaurantes: ['Massa Bistro','Istambul kebab','Yuksel Balik','Ocak']
      },
      { id:5,
        img:'',
        cultura:'Mediterránea',
        region: 'Líbano',
        descripcion: 'La gastronomía del Líbano es generosa, abundante, colorida e increíblemente diversa; celebra la frescura de la temporada y concentra su atención en las hierbas aromáticas, las especias, el ajo, el limón y el aceite de oliva.',
        platosPrincipales: ['Tabule','BABAGANOUSH','Shawarma de Pollo'],
        ingredientes: [{nombre:'Pollo', categoria:'Proteinas'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Trigo', categoria:'Cereales'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Berenjenas', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Garbanzo', categoria:'Legumbres'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Canela', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Yogurt', categoria:'Lacteos'},
                      {nombre:'Azucar', categoria:'Carbohidratos'},
                      {nombre:'Cilantro', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hierbabuena', categoria:'Condimentos'}],
        restaurantes: ['La cigale','Barometre','Kabab 1961','Kababji']
      },
      { id:6,
        img:'',
        cultura:'Mediterránea',
        region: 'Egipto',
        descripcion: 'La cocina de Egipto incluye cocizos de alubias blancas y falafel con carne de ternera, cordero y la paloma que también es popular. Sus postres no son tan ricos y contundentes, como los de muchos otros países árabes, pero su cocina es similar y la mayoría de los platos tienen el mismo nombre de todo el Oriente Medio.',
        platosPrincipales: ['Ful Medames','Koshari','Baba Ganoush'],
        ingredientes: [{nombre:'Habas', categoria:'Legumbres'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pasta', categoria:'Carbohidratos'},
                      {nombre:'Oréngano', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Berenjena', categoria:'Vegetales'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Queso Feta', categoria:'Proteinas'},
                      {nombre:'Vinagre de Jerez', categoria:'Condimentos'}],
        restaurantes: ['El fishawy','FelFela','Elezba','Shark','Bedouin Lodge']
      },
      { id:7,
        img:'',
        cultura:'Mediterránea',
        region: 'Marruecos',
        descripcion: 'Es un tipo de cocina donde abundan las verduras y frutas, especias, cereales, legumbres y en general poca carne. Se caracteriza por la combinación de los sabores dulce y salado, algo que está muy presente también en la gastronomía típica de Extremo Oriente.',
        platosPrincipales: ['Cous Cous','Harissa','Ras el hanout'],
        ingredientes: [{nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Curry', categoria:'Condimentos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Pimienta Negra', categoria:'Condimentos'},
                      {nombre:'Lomo de Caballa', categoria:'Proteinas'},
                      {nombre:'Harina de Maiz', categoria:'Cereales'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Queso Colot', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hoas de Lechuga', categoria:'Hortalizas'}],
        restaurantes: ['Chez Chegrouni','Toubkal','Dar Mimoun','Le Marrakchi']
      },
      { id:8,
        img:'',
        cultura:'Mediterránea',
        region: 'Malta',
        descripcion: 'La cocina maltesa se caracteriza por los sabores intensos y especiados de sus platos, en los que los principales ingredientes son el pescado, las verduras, la carne, la pasta, el hojaldre, los dátiles y el aceite de oliva.',
        platosPrincipales: ['Pastizzi','Gbejniet','Hobza'],
        ingredientes: [{nombre:'Alubia', categoria:'Legumbres'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Trigo', categoria:'Cereales'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Berenjenas', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Queso de Cabra', categoria:'Proteinas'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Canela', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Yogurt', categoria:'Lacteos'},
                      {nombre:'Azucar', categoria:'Carbohidratos'},
                      {nombre:'Cilantro', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hierbabuena', categoria:'Condimentos'}],
        restaurantes: ['Ta Marija','Caviar & Bull','Madliena Lodge','Aki']
      }, //Gastronomia Latinoamericana
      { id:9,
        img:'',
        cultura:'Latinoamericana',
        region: 'Colombia',
        descripcion: 'La gastronomía colombiana se caracteriza por la variedad de sus productos y la cantidad de opciones interesantes. Se trata de una cocina múltiple, original y versátil, que ofrece una mezcla de colores, sabores y aromas para enamorar a cualquier comensal.',
        platosPrincipales: ['Ajíaco','Bandeja Paisa','Lechona'],
        ingredientes: [{nombre:'Cebolla', categoria:'verdura'},
                      {nombre:'Huevos', categoria:'Proteina'},
                      {nombre:'Papas', categoria:'Tubérculo'},
                      {nombre:'Carnde de cerdo', categoria:'Proteina'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Aguacate', categoria:'Fruta'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Arracacha', categoria:'Tuberculo'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Pollo', categoria:'Proteina'},
                      {nombre:'Conejo', categoria:'Proteina'},
                      {nombre:'Fríjol', categoria:'Legumbres'},
                      {nombre:'Arveja', categoria:'Legumbres'},
                      {nombre:'Yuca', categoria:'Tubérculo'},
                      {nombre:'Platano', categoria:'Frutas'}],
        restaurantes: ['LEO','Harry Sasson','El Chato','Criterion']
      },
      { id:10,
        img:'',
        cultura:'Latinoamericana',
        region: 'Mexico',
        descripcion: 'La gastronomía mexicana es el conjunto de platillos y técnicas culinarias de México, las cuales forman parte de su tradición y cultura. La cocina mexicana forma parte de la vida diaria de los mexicanos, por eso ha sido enriquecida por las aportaciones de generación en generación y por las diferentes regiones del país.',
        platosPrincipales: ['Tacos','Birria de Res','Pozole'],
        ingredientes: [{nombre:'Cebolla', categoria:'verdura'},
                      {nombre:'Huevos', categoria:'Proteina'},
                      {nombre:'Chiles', categoria:'Fruta'},
                      {nombre:'Carnde de cerdo', categoria:'Proteina'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Jitomates', categoria:'Frutas'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Maiz', categoria:'Cereales'},
                      {nombre:'Epazote', categoria:'Condimentos'},
                      {nombre:'Pollo', categoria:'Proteina'},
                      {nombre:'Nopal', categoria:'Vegetales'},
                      {nombre:'Fríjol', categoria:'Legumbres'},
                      {nombre:'Guisantes', categoria:'Legumbres'},
                      {nombre:'Cilantro', categoria:'Condimentos'},
                      {nombre:'Platano', categoria:'Fruta'}],
        restaurantes: ['Pujol','Quintonil','Sud 777','Rosetta','Máximo Bistrot']
      },
      { id:11,
        img:'',
        cultura:'Latinoamericana',
        region: 'Argentina',
        descripcion: 'La gastronomía argentina es una de las más sabrosas del mundo, debido a las increíbles materias primas que emplea, sobre todo la carne. La rica cultura gastronómica argentina combina los sabores de las cocinas europeas –especialmente la española y la italiana– con los de la cocina criolla e indígena, y es conocida por sus carnes de res de altísima calidad. Los platos varían mucho de una región a otra, pero hay algunos que son muy populares en todo el país.',
        platosPrincipales: ['El locro','El bife de chorizo','Choripan'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Maiz', categoria:'Cereales'},
                      {nombre:'Carne de Res', categoria:'Tubérculo'},
                      {nombre:'Carnde de cerdo', categoria:'Proteinas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimientos', categoria:'Condimentos'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Queso', categoria:'Tuberculo'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Chimichurri', categoria:'Condimentos'},
                      {nombre:'Bife de Chorizo', categoria:'Proteina'},
                      {nombre:'Porotos', categoria:'Legumbres'},
                      {nombre:'Calabaza', categoria:'Vegetales'},
                      {nombre:'Chorizo Criollo', categoria:'Proteinas'}],
        restaurantes: ['Tegui','Don Julio','Chila','El Baqueano','Aramburu']
      },
      { id:12,
        img:'',
        cultura:'Latinoamericana',
        region: 'Brasil',
        descripcion: 'La gastronomía de Brasil está llena de influencias portuguesas, alemanas, italianas, árabes, indígenas y africanas. Éstas, combinadas con la auténtica cocina brasileña, han dado como resultado una alimentación rica, colorida y muy sabrosa.',
        platosPrincipales: ['Feijoada','Moqueca de peixe','Farofa'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Cilantro', categoria:'Condimentos'},
                      {nombre:'Lomo de cerdo', categoria:'Proteinas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento Rojo', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Lomo de Pescado', categoria:'Cereales'},
                      {nombre:'Ñame', categoria:'Tuberculos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Harina de mandioca', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Fríjol Negro', categoria:'Legumbres'},
                      {nombre:'Panceta', categoria:'Proteinas'},
                      {nombre:'Yuca', categoria:'Tubérculo'},
                      {nombre:'Coco', categoria:'Fruta'}],
        restaurantes: ['Evvai','Maní','Metzi','D.O.M.','Charco']
      },
      { id:13,
        img:'',
        cultura:'Latinoamericana',
        region: 'Chile',
        descripcion: 'La gastronomía de Chile es producto de la mezcla entre la tradición indígena y el aporte colonial español, combinando sus alimentos, costumbres y hábitos culinarios. A lo largo del tiempo, ha tenido aportes menores de cocinas europeas por parte de inmigrantes, como la alemana e italiana; sin embargo, en el siglo xx tuvo una importante y marcada influencia de la cocina francesa.  Estos elementos conformaron lo que se conoce como «cocina criolla chilena», la cual destaca por sus variados sabores, ingredientes y colores,  resultado de la diversidad geográfica del país,',
        platosPrincipales: ['Ajíaco','Arrollado huaso','Caldillo de congrio'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Vino Blanco', categoria:'Bebidas Alcoholicas'},
                      {nombre:'Papas', categoria:'Tubérculos'},
                      {nombre:'Carnde de Res', categoria:'Proteina'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimientos', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Zanahorias', categoria:'Verduras'},
                      {nombre:'Comino', categoria:'Condimentos'},
                      {nombre:'Orégano', categoria:'Condimentos'},
                      {nombre:'Tocino', categoria:'Proteinas'},
                      {nombre:'Almejas', categoria:'Proteinas'},
                      {nombre:'Zapallo', categoria:'Vegetales'},
                      {nombre:'Ají', categoria:'Condimentos'},
                      {nombre:'Congrio', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'}],
        restaurantes: ['Boragó','Naoki','99. restaurant ','Espíritu Santo']
      },
      { id:14,
        img:'',
        cultura:'Latinoamericana',
        region: 'Urugay',
        descripcion: 'La cocina de Uruguay se diferencia de la cocina latinoamericana, pero tiene muchos puntos en contacto con la cocina argentina. Su principal característica es la pluralidad de influencias culturales, debido a las corrientes migratorias europeas que poblaron el país, mezclándose con tradiciones autóctonas y regionales.',
        platosPrincipales: ['Asado','Capeletis a la Caruso','Chivito'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Pasta Capeleti', categoria:'Carbohidratos'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Carnde de cerdo', categoria:'Proteina'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Jamón', categoria:'Proteinas'},
                      {nombre:'Carne de Res', categoria:'Tuberculo'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Pollo', categoria:'Proteinas'},
                      {nombre:'Ternera', categoria:'Proteinas'},
                      {nombre:'Salchichas', categoria:'Proteinas'},
                      {nombre:'Arveja', categoria:'Legumbres'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Aceitunas', categoria:'Vegetales'}],
        restaurantes: ['La Huella','La Bourgogne','Café Misterio','Lo de Tere']
      },
      { id:15,
        img:'',
        cultura:'Latinoamericana',
        region: 'Perú',
        descripcion: 'La cocina peruana es una de las cocinas más importantes en el mundo y un ejemplo de cocina fusión, debido a su larga historia multicultural, la cual se basa en la mezcla de los conocimientos culinarios del antiguo Perú —con sus propias técnicas y potajes— con la cocina hispana en su variante muy fuertemente influenciada por 762 años de presencia árabe en la península ibérica, y con importante aporte de las costumbres culinarias llevadas de la costa atlántica del África subsahariana por los esclavos.',
        platosPrincipales: ['Ceviche','Llomo Saltado','Causa Limeña'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Papas', categoria:'Tubérculos'},
                      {nombre:'Limones', categoria:'Frutas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Ají', categoria:'Condimentos'},
                      {nombre:'Vinagre', categoria:'Condimentos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Pollo', categoria:'Proteinas'},
                      {nombre:'Gallina', categoria:'Proteinas'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Arveja', categoria:'Legumbres'},
                      {nombre:'Aceitunas', categoria:'Vegetales'},
                      {nombre:'Maiz', categoria:'Cereales'}],
        restaurantes: ['Central','Maido','Mayta','Rafae','Astrid & Gastón']
      },
      { id:16,
        img:'',
        cultura:'Latinoamericana',
        region: 'Venezuela',
        descripcion: 'La gastronomía de Venezuela es una variada forma de preparar comidas y bebidas elaboradas en dicho país, constituyendo el resultado de la mezcla cultural y gastronómica procedentes de Europa (especialmente de España, Italia, Alemania, Francia, Países Bajos y Portugal) y África (a través de las poblaciones de esclavos llevados por los españoles) con la gastronomía de los pueblos indígenas de Venezuela.',
        platosPrincipales: ['Pabellón criollo','Hallacas','Cachapas'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Aceitunas', categoria:'Vegetales'},
                      {nombre:'Carnde de cerdo', categoria:'Proteina'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Harina de Trigo', categoria:'Cereales'},
                      {nombre:'Orégano', categoria:'Condimentos'},
                      {nombre:'Maiz', categoria:'Cereales'},
                      {nombre:'Carne de Res', categoria:'Proteinas'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Fríjol Negro', categoria:'Legumbres'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Vinagre', categoria:'Condimentos'},
                      {nombre:'Platano', categoria:'Fruta'}],
        restaurantes: ['Beaujon Patisserie','La Sifrina Maizera','Panela Haus','Bistró Veg']
      }, //Gastronomia Francesa
      { id:17,
        img:'',
        cultura:'Frncesa',
        region: 'Paris',
        descripcion: 'En París se originó y desarrolló la Alta Cocina (Haute cuisine) de la mano de reputados chefs como Marie-Antoine Carême, François Pierre de la Varenne, Auguste Escoffier, François Vatel o Fernand Point entre muchos otros. La gastronomía de París vivió su auge durante los siglos XIX y XX, influyendo decisivamente en la gastronomía mundial',
        platosPrincipales: ['Soupe a L’oignon','Escargots','Ratatouille'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Patatas', categoria:'Tuberculos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimientos', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Almendras', categoria:'Cereales'},
                      {nombre:'Vinagre de Jerez', categoria:'Condimentos'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Pollo', categoria:'Proteinas'},
                      {nombre:'Escargots', categoria:'Proteinas'},
                      {nombre:'Judias', categoria:'Legumbres'},
                      {nombre:'Zanahoria', categoria:'Verduras'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'}],
        restaurantes: ['Plénitude','L’Ambroisie','Kei','Arpège']
      },
      { id:18,
        img:'',
        cultura:'Francesa',
        region: 'Lyon',
        descripcion: 'Lyon es conocida por su gastronomía, Curnonsky en su libro Principe des gastronomes consagró a Lyon, «Capital mundial de la gastronomía». El crítico gastronómico alemán Jörg Zipprick dice: «La cultura gastronómica no se puede medir por el número de buenos restaurantes, aunque Lyon está muy bien situado, se mide en su vida diaria, y allí no hay foto, Lyon es el número uno.',
        platosPrincipales: ['Foie de veau à la lyonnaise','Andouillette','Rosette de Lyon'],
        ingredientes: [{nombre:'Cebollas', categoria:'Verduras'},
                      {nombre:'Vino Blanco', categoria:'Bebidas Alcoholicas'},
                      {nombre:'Patatas', categoria:'Tuberculos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimientos', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Cerveza', categoria:'Bebidas Alcoholicas'},
                      {nombre:'Lomo de Cerdo', categoria:'Proteinas'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Jamón', categoria:'Proteinas'},
                      {nombre:'Salchichas', categoria:'Proteinas'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Col Gallega', categoria:'Hotalizas'},
                      {nombre:'Chorizo Ahumado', categoria:'Proteinas'}],
        restaurantes: ['Agastache','Canaima','Burgundy by Matthieu','Mère Brazier']
      },
      { id:19,
        img:'',
        cultura:'Francesa',
        region: 'Marsella',
        descripcion: 'La cocina provenzal ha deleitado las papilas gustativas de jóvenes y mayores durante generaciones y se ha convertido en parte del patrimonio de la gastronomía francesa. Homenajeamos estas especialidades regionales que el mundo nos envidia.... En el menú: aceite de oliva, verduras bañadas por el sol y sabores inimitables!',
        platosPrincipales: ['La Bouillabaise','Omelette aux truffes','Tapenade'],
        ingredientes: [{nombre:'Cebollas', categoria:'Vegetales'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Almejas', categoria:'Proteinas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Aceitunas', categoria:'Vegetales'},
                      {nombre:'Oréngano', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hierbabuena', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Queso Feta', categoria:'Proteinas'},
                      {nombre:'Vinagre de Jerez', categoria:'Condimentos'}],
        restaurantes: ['Chez Fonfon','Les trois Forts','El jardin de Montgrand','lod´in','Alcyone']
      },
      { id:20,
        img:'',
        cultura:'Francesa',
        region: 'Touluse',
        descripcion: 'Toulouse, conocida como la Ville Rose por sus fachadas de ladrillo rosa, se encuentra en el corazón del suroeste. Combinando un rico patrimonio, el encanto del sur y lo mejor del art de vivre francés, en esta ciudad proliferan las citas culturales y festividades. La ciudad, atravesada por el Canal du Midi y el por río Garona, es un hervidero de cultura y gastronomía.',
        platosPrincipales: ['Cassoulet','Saucisse de Toulouse','La Fénétra'],
        ingredientes: [{nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Pato', categoria:'Proteinas'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Pimienta Negra', categoria:'Condimentos'},
                      {nombre:'salchicha tolosana', categoria:'Proteinas'},
                      {nombre:'Harina de Maiz', categoria:'Cereales'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Queso Colot', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hojas de Lechuga', categoria:'Hortalizas'}],
        restaurantes: ['Petit Voyage','Le New Goa','Degus&co','Trioka Royal']
      },
      { id:21,
        img:'',
        cultura:'Francesa',
        region: 'Carcasona',
        descripcion: 'La cocina de Carcassonne es principalmente una combinación de recetas locales y regiones cercanas, incluyendo los influyentes estilos culinarios españoles, italianos y provenzales. Se caracteriza por su uso generoso de hierbas frescas y especias, así como aceite de oliva, queso y vino tinto local.',
        platosPrincipales: ['La fougasse aux fritons','Le foie sec','Le cassoulet'],
        ingredientes: [{nombre:'Hígado', categoria:'Proteinas'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Trigo', categoria:'Cereales'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Berenjenas', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Fríjol Blanco', categoria:'Legumbres'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Canela', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Yogurt', categoria:'Lacteos'},
                      {nombre:'Azucar', categoria:'Carbohidratos'},
                      {nombre:'Cilantro', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Hierbabuena', categoria:'Condimentos'}],
        restaurantes: ['Comte Roger','Domiane d´Auriac','Le Puits du Trésor','La Table de Franck Putelat']
      },
      { id:22,
        img:'',
        cultura:'Francesa',
        region: 'Reims',
        descripcion: 'Reims es una ciudad escénica francesa bien conocida por sus restaurantes de lujo y encantadores cafés de nivel internacional. El restaurante La Table Anna es la casa de comidas más demandada de la ciudad siendo el lugar de primera elección entre cientos de otros entre los residentes locales y los huéspedes extranjeros. Por su interior el restaurante se asemeja a un bistro francés clásico.',
        platosPrincipales: ['Rillette de sardinas','souffle de queso','Vichyssoise'],
        ingredientes: [{nombre:'Sardinas', categoria:'Proteinas'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento Rojo', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pasta', categoria:'Carbohidratos'},
                      {nombre:'Oréngano', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Berenjena', categoria:'Vegetales'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Queso Crema', categoria:'Proteinas'},
                      {nombre:'Vinagre de Jerez', categoria:'Condimentos'}],
        restaurantes: ['Assiette Champenoise','Le Royal','Le Parc Les Crayères','La Grande Georgette',]
      },
      { id:23,
        img:'',
        cultura:'Francesa',
        region: 'Burdeos',
        descripcion: 'La comida típica de Burdeos es una fusión de la cocina francesa clásica con influencias regionales. Aquí, el ingrediente estrella es la carne de res, especialmente el cordero y el buey. La región de Aquitania es famosa por su ganadería y pastos verdes, lo que da lugar a carnes tiernas y sabrosas',
        platosPrincipales: ['Magret de Canard','Entrecot a la bordelesa','Cordero de Pauillac à la Persillade'],
        ingredientes: [{nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Pato', categoria:'Proteinas'},
                      {nombre:'Curry', categoria:'Condimentos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Cordero', categoria:'Proteinas'},
                      {nombre:'Pimienta Negra', categoria:'Condimentos'},
                      {nombre:'Lomo de Caballa', categoria:'Proteinas'},
                      {nombre:'Harina de Maiz', categoria:'Cereales'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Queso Colot', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Vino Tinto', categoria:'Bebidas Alcohólicas'}],
        restaurantes: ['Bo-tannique','Lil´Home','Akashi','L´Oiseau Bleu']
      },
      { id:24,
        img:'',
        cultura:'Francesa',
        region: 'Narbona',
        descripcion: 'La gastronomía de Narbona mejor valorada, es la especializado en cocina italiana, particularmente en pizzas. por sucercania a ciudades de Italia, sin embargo, su escencia francesa nos deja delitar mas de 300 platos, con un servicio de mesa clásico, tradicional y lujoso.',
        platosPrincipales: ['Bogavante a la Americana','Magrait de Pato','Steak Tartar'],
        ingredientes: [{nombre:'Alubia', categoria:'Legumbres'},
                      {nombre:'Limón', categoria:'Frutas'},
                      {nombre:'Trigo', categoria:'Cereales'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Berenjenas', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Pato', categoria:'Proteinas'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Canela', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Yogurt', categoria:'Lacteos'},
                      {nombre:'Azucar', categoria:'Carbohidratos'},
                      {nombre:'Cilantro', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Vinagre Balsamico', categoria:'Condimentos'}],
        restaurantes: ['Le Petit Comptoir','La Tulipe Noire','Au Lavoir','La Table Lionel Giraud']
      }, //Gastronomía Italiana
      { id:25,
        img:'',
        cultura:'Italiana',
        region: 'Roma',
        descripcion: 'La gastronomía romana cambió a través de la larga duración (más de un milenio) de su antigua civilización. Sus hábitos se vieron influenciados por la cultura griega, los cambios políticos de monarquía a república, y de ahí a imperio, y la enorme expansión de este último, que trajo muchos hábitos culinarios nuevos y técnicas de cocina provincial. Al principio, las diferencias entre las clases sociales no eran tan significativas, pero la distancia entre ellas creció junto con el imperio',
        platosPrincipales: ['Spaguetti all Carbonara','Carpaccio','Risotto'],
        ingredientes: [{nombre:'Cebolla', categoria:'Verduras'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Espaguetti', categoria:'Carbohidratos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimientos', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Carne de Ternera', categoria:'Proteinas'},
                      {nombre:'Queso Peccorino', categoria:'Proteinas'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Guanccialle', categoria:'Proteinas'},
                      {nombre:'Judias', categoria:'Legumbres'},
                      {nombre:'Albahaca', categoria:'Condimentos'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'}],
        restaurantes: ['Bencò','Casa Bleve','Rinaldi al Quirinale','Luciano Cucina Italiana']
      },
      { id:26,
        img:'',
        cultura:'Italiana',
        region: 'Florencia',
        descripcion: 'La gastronomía de Florencia, como casi toda la cocina toscana, es de orígenes muy simples y pobres. Se basa en productos de la riquísima tierra toscana que hacen de la cocina de esta región una de las mejores de toda Italia. La gastronomía de Florencia tiene un papel muy importante y para bien. ¡Nadie se cansa de saborearla!',
        platosPrincipales: ['Bistecca alla Fiorentina','Pappardelle sulla leppre','Ribollita'],
        ingredientes: [{nombre:'Cebollas', categoria:'Verduras'},
                      {nombre:'Vino Blanco', categoria:'Bebidas Alcoholicas'},
                      {nombre:'Fetuccini', categoria:'Carbohidratos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimientos', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Mantequilla', categoria:'Grasas'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Bistec de Ternera', categoria:'Proteinas'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Jamón', categoria:'Proteinas'},
                      {nombre:'Salchichas', categoria:'Proteinas'},
                      {nombre:'Queso', categoria:'Proteinas'},
                      {nombre:'Col', categoria:'Hotalizas'},
                      {nombre:'Pepperoni', categoria:'Proteinas'}],
        restaurantes: ['Nugolo','Essenziale','Winter Garden Florence','Vitique']
      },
      { id:27,
        img:'',
        cultura:'Italiana',
        region: 'Nápoles',
        descripcion: 'La gastronomía de Nápoles (en italiano mencionada como cucina napoletana) es un conjunto de platos y costumbres culinarias típicos de la ciudad de Nápoles, en Italia. Tiene raíces históricas muy antiguas que se remontan al período greco-romano, y a lo largo de los siglos se ha enriquecido con la influencia de las diferentes culturas y dominaciones que se han sucedido en la ciudad y en el territorio circunstante. Además, es posible añadir a la memoria histórica culinaria de Nápoles la creatividad propia de sus habitantes, que ha permitido «fusionar» diferentes estilos y tradiciones, todos ellos guardados por su población a lo largo de la historia con rigor.',
        platosPrincipales: ['Pizza Napolitana','Casatiello','Spaguetti alle Vongole'],
        ingredientes: [{nombre:'Cebollas', categoria:'Vegetales'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Jamón de Cerdo', categoria:'Proteinas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Perejil', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Aceitunas', categoria:'Vegetales'},
                      {nombre:'Almejas', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Queso parmigiano', categoria:'Proteinas'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Espaguetti', categoria:'Carbohidratos'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Queso Mozzarella', categoria:'Proteinas'},
                      {nombre:'Orégano', categoria:'Condimentos'}],
        restaurantes: ['Essencia Restaurant','Palazzo Petrucci Pizzeria','Taverna Estia','Urubamba','Palazzo Petrucci']
      },
      { id:28,
        img:'',
        cultura:'Italiana',
        region: 'Bolonia',
        descripcion: 'Al igual que en el resto de Italia, Bolonia se caracteriza por una cocina dedicada a las pastas y los embutidos típicos. Así como también una variada pastelería que reúne las características de todo buen dulce: masa esponjosa y rellenos que te hacen ver las estrellas de lo fabulosos que son.',
        platosPrincipales: ['Cotoletta alla bolognese','Tortellini in brodo','Crescentine'],
        ingredientes: [{nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Mortadella', categoria:'Proteinas'},
                      {nombre:'Salami', categoria:'Proteinas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Totellini', categoria:'Carbohidratos'},
                      {nombre:'Chuleta de Ternera', categoria:'Proteinas'},
                      {nombre:'Pimienta Negra', categoria:'Condimentos'},
                      {nombre:'Jamón de Parma', categoria:'Proteinas'},
                      {nombre:'Harina de Maiz', categoria:'Cereales'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Queso Squacquerone', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Antipasto', categoria:'Condimentos'}],
        restaurantes: ['Fourghetti','Posta','Acqua Pazza','I Carracci']
      },
      { id:29,
        img:'',
        cultura:'Italiana',
        region: 'Verona',
        descripcion: 'La gastronomía de Verona se basa en una cocina de origen que oscila entre el estilo rural y el costero, y que representa una diversidad fruto de muchas culturas, así como de paisajes y climas. La cocina española está fuertemente influida a lo largo de su historia por los pueblos que conquistan su territorio, así como de los pueblos que posteriormente conquista y coloniza.',
        platosPrincipales: ['Risotto con Tastasal','Pastissada de Caval','Gnocchi de Patata'],
        ingredientes: [{nombre:'Carne de Caballo', categoria:'Proteinas'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Carde de Cerdo', categoria:'Proteinas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Berenjenas', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Patata Gallega', categoria:'Carbohidratos'},
                      {nombre:'Panceta', categoria:'Proteinas'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Queso Grana Padano', categoria:'Proteinas'},
                      {nombre:'Harina de Trigo', categoria:'Cereales'},
                      {nombre:'Zanahoria', categoria:'Verduras'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Romero', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Vino Blanco', categoria:'Bebidas Alcohólicas'}],
        restaurantes: ['Yard Restaurant','Amistà','Caffè Dante Bistrot','Ponte Pietra']
      },
      { id:30,
        img:'',
        cultura:'Italiana',
        region: 'Milán',
        descripcion: 'La gastronomía de Milán una de las más valoradas, es una especialización  en cocina italiana. A diferencia de otras regiones de Italia, en Milán se consume mucho más arroz que pasta, sin embargo, su esencia Italiana nos deja deleitar platos, con un servicio de mesa clásico, tradicional y lujoso.',
        platosPrincipales: ['Risotto Milanés','Cassoeula','Busecca'],
        ingredientes: [{nombre:'Carne de Cerdo', categoria:'Proteinas'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Repollo', categoria:'Hortalizas'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento Rojo', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Callos', categoria:'Proteinas'},
                      {nombre:'Oréngano', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Arroz', categoria:'Cereales'},
                      {nombre:'Berenjena', categoria:'Vegetales'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Pimienta', categoria:'Condimentos'},
                      {nombre:'Queso Mascarpone', categoria:'Proteinas'},
                      {nombre:'Queso Gorgonzola', categoria:'Proteinas'}],
        restaurantes: ['La Società Milano','Belé','La Corte Gourmet','Il Marchese - Osteria Mercato Liquori',]
      },
      { id:31,
        img:'',
        cultura:'Italiana',
        region: 'Génova',
        descripcion: 'La cocina Genovesa ha deleitado las papilas gustativas de jóvenes y mayores durante generaciones y se ha convertido en parte del patrimonio de la gastronomía Italiana. Homenajeamos estas especialidades regionales que el mundo nos envidia. En el menú: aceite de oliva, verduras bañadas por el sol y sabores inimitables!',
        platosPrincipales: ['Pesto Genovese','Trofie al pesto','Foccacia genovese'],
        ingredientes: [{nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Queso Pecorino', categoria:'Proteinas'},
                      {nombre:'Pesto', categoria:'Condimentos'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Pimiento', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Cordero', categoria:'Proteinas'},
                      {nombre:'Piñones', categoria:'Legumbres'},
                      {nombre:'Albahaca', categoria:'Condimentos'},
                      {nombre:'Harina', categoria:'Cereales'},
                      {nombre:'Laurel', categoria:'Condimentos'},
                      {nombre:'Tomillo', categoria:'Condimentos'},
                      {nombre:'Queso Parmesano', categoria:'Proteinas'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Vino Tinto', categoria:'Bebidas Alcohólicas'}],
        restaurantes: ['Soho','Santa Teresa','Hostaria Ducale','San Giorgio']
      },
      { id:32,
        img:'',
        cultura:'Italiana',
        region: 'Palermo',
        descripcion: 'La comida de Palermo se caracteriza por las influencias de árabes, romanos, normandos, griegos, españoles, judíos y otros pueblos; una mezcla que es especialmente evidente en la comida callejera. En Palermo se toman muy en serio la comida callejera (y la comida en general).',
        platosPrincipales: ['Sfincione','Caponata','Pasta al Forno'],
        ingredientes: [{nombre:'Anchoas', categoria:'Proteinas'},
                      {nombre:'Pasta', categoria:'Carbohidratos'},
                      {nombre:'Piñones', categoria:'Legumbres'},
                      {nombre:'Aceite de Oliva', categoria:'Grasas'},
                      {nombre:'Sal', categoria:'Minerales'},
                      {nombre:'Tomates', categoria:'Vegetales'},
                      {nombre:'Berenjenas', categoria:'Vegetales'},
                      {nombre:'Ajo', categoria:'Condimentos'},
                      {nombre:'Pan', categoria:'Cereales'},
                      {nombre:'Queso Ricotta', categoria:'Proteinas'},
                      {nombre:'Cebolla', categoria:'Condimentos'},
                      {nombre:'Salami', categoria:'Proteinas'},
                      {nombre:'Huevos', categoria:'Proteinas'},
                      {nombre:'Orégano', categoria:'Condimentos'},
                      {nombre:'Queso Tuma', categoria:'Carbohidratos'},
                      {nombre:'Albahaca', categoria:'Condimentos'},
                      {nombre:'Perejil', categoria:'Condimentos'},
                      {nombre:'Vinagre', categoria:'Condimentos'}],
        restaurantes: ['Mec Restaurant','L´Ottava Nota','Buatta Cucina Popolana','Bebop']
      }
    ];
    return{gastronomias};
  }
}
